apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
  namespace: default
spec:
  serviceName: "ollama"
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        resources:
          requests:
            cpu: "4000m"
            memory: "8Gi 
          limits:
            cpu: "14000m"
            memory: "22Gi"
            # nvidia.com/gpu: "0"
        volumeMounts:
        - name: ollama-volume
          mountPath: /root/.ollama
        tty: true
        # command: ["/bin/sh", "-c"]
        # args:
        #   - |
        #     # /usr/bin/ollama serve &
        #     echo "Starting Ollama in the background..."
        #     sleep 15
            
        #     echo "Waiting for Ollama to be ready..."
        #     sleep 15
            
        #     echo "Pulling model..."
        #     ollama pull deepseek-r1:7b
            
        #     echo "Ollama setup complete." # Running foreground process..."
        #     ollama serve &
  volumeClaimTemplates:
  - metadata:
      name: ollama-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 30Gi
