apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: private-chatbot
  name: private-chatbot-pvc
  namespace: private-chatbot
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
